course = "pyThon pRograMming"
print(course.upper())
print(course.lower())
print(course.title())
print(course.swapcase())
print(course.rstrip())
print(course.find("gram"))
print(course.replace("o", "s"))
print("th" in course)
print("swift" not in course)
